
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo;


our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo->mk_accessors( qw(capability interfaceMTU vlanRangeAvailability suggestedVLANRange vlanTranslation));

OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'capability' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::string',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'capability',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                         'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'interfaceMTU' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::int',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'interfaceMTU',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                           'type' => 'int|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'suggestedVLANRange' => bless( {
                                                                 'class' => 'XML::Pastor::Builtin::string',
                                                                 'metaClass' => 'OSCARS::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'suggestedVLANRange',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                 'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'vlanRangeAvailability' => bless( {
                                                                    'class' => 'XML::Pastor::Builtin::string',
                                                                    'metaClass' => 'OSCARS::Pastor::Meta',
                                                                    'minOccurs' => '0',
                                                                    'name' => 'vlanRangeAvailability',
                                                                    'scope' => 'local',
                                                                    'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                    'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                  }, 'XML::Pastor::Schema::Element' ),
                                  'vlanTranslation' => bless( {
                                                              'class' => 'XML::Pastor::Builtin::boolean',
                                                              'metaClass' => 'OSCARS::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'vlanTranslation',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                              'type' => 'boolean|http://www.w3.org/2001/XMLSchema'
                                                            }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'capability',
                                 'interfaceMTU',
                                 'vlanRangeAvailability',
                                 'suggestedVLANRange',
                                 'vlanTranslation'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'CtrlPlaneSwitchingCapabilitySpecificInfo',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<capability>()      - See L<XML::Pastor::Builtin::string>.

=item B<interfaceMTU>()      - See L<XML::Pastor::Builtin::int>.

=item B<suggestedVLANRange>()      - See L<XML::Pastor::Builtin::string>.

=item B<vlanRangeAvailability>()      - See L<XML::Pastor::Builtin::string>.

=item B<vlanTranslation>()      - See L<XML::Pastor::Builtin::boolean>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
