
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::ns002::Type::CtrlPlaneSwcapContent;

use OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::ns002::Type::CtrlPlaneSwcapContent->mk_accessors( qw(switchingcapType encodingType switchingCapabilitySpecificInfo));

OSCARS::ns002::Type::CtrlPlaneSwcapContent->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::ns002::Type::CtrlPlaneSwcapContent',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'encodingType' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::string',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'name' => 'encodingType',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                           'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'switchingCapabilitySpecificInfo' => bless( {
                                                                              'class' => 'OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo',
                                                                              'metaClass' => 'OSCARS::Pastor::Meta',
                                                                              'name' => 'switchingCapabilitySpecificInfo',
                                                                              'scope' => 'local',
                                                                              'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                              'type' => 'CtrlPlaneSwitchingCapabilitySpecificInfo|http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
                                                                            }, 'XML::Pastor::Schema::Element' ),
                                  'switchingcapType' => bless( {
                                                               'class' => 'XML::Pastor::Builtin::string',
                                                               'metaClass' => 'OSCARS::Pastor::Meta',
                                                               'name' => 'switchingcapType',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                               'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                             }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'switchingcapType',
                                 'encodingType',
                                 'switchingCapabilitySpecificInfo'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'CtrlPlaneSwcapContent',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::ns002::Type::CtrlPlaneSwcapContent>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<encodingType>()      - See L<XML::Pastor::Builtin::string>.

=item B<switchingCapabilitySpecificInfo>()      - See L<OSCARS::ns002::Type::CtrlPlaneSwitchingCapabilitySpecificInfo>.

=item B<switchingcapType>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
