
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::ns002::Type::CtrlPlaneLinkContent;

use OSCARS::ns002::Type::CtrlPlaneAdministrativeGroup;
use OSCARS::ns002::Type::CtrlPlaneSwcapContent;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::ns002::Type::CtrlPlaneLinkContent->mk_accessors( qw(_id remoteLinkId trafficEngineeringMetric capacity maximumReservableCapacity minimumReservableCapacity granularity unreservedCapacity linkProtectionTypes administrativeGroups SwitchingCapabilityDescriptors));

# Attribute accessor aliases

sub id { &_id; }

OSCARS::ns002::Type::CtrlPlaneLinkContent->XmlSchemaType( bless( {
                 'attributeInfo' => {
                                    'id' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::string',
                                                   'metaClass' => 'OSCARS::Pastor::Meta',
                                                   'name' => 'id',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                   'type' => 'string|http://www.w3.org/2001/XMLSchema',
                                                   'use' => 'required'
                                                 }, 'XML::Pastor::Schema::Attribute' )
                                  },
                 'attributePrefix' => '_',
                 'attributes' => [
                                   'id'
                                 ],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::ns002::Type::CtrlPlaneLinkContent',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'SwitchingCapabilityDescriptors' => bless( {
                                                                             'class' => 'OSCARS::ns002::Type::CtrlPlaneSwcapContent',
                                                                             'metaClass' => 'OSCARS::Pastor::Meta',
                                                                             'name' => 'SwitchingCapabilityDescriptors',
                                                                             'scope' => 'local',
                                                                             'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                             'type' => 'CtrlPlaneSwcapContent|http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
                                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'administrativeGroups' => bless( {
                                                                   'class' => 'OSCARS::ns002::Type::CtrlPlaneAdministrativeGroup',
                                                                   'maxOccurs' => 'unbounded',
                                                                   'metaClass' => 'OSCARS::Pastor::Meta',
                                                                   'minOccurs' => '0',
                                                                   'name' => 'administrativeGroups',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                   'type' => 'CtrlPlaneAdministrativeGroup|http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
                                                                 }, 'XML::Pastor::Schema::Element' ),
                                  'capacity' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::string',
                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'capacity',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                       'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'granularity' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'metaClass' => 'OSCARS::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'granularity',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'linkProtectionTypes' => bless( {
                                                                  'class' => 'XML::Pastor::Builtin::string',
                                                                  'maxOccurs' => 'unbounded',
                                                                  'metaClass' => 'OSCARS::Pastor::Meta',
                                                                  'minOccurs' => '0',
                                                                  'name' => 'linkProtectionTypes',
                                                                  'scope' => 'local',
                                                                  'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                  'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                }, 'XML::Pastor::Schema::Element' ),
                                  'maximumReservableCapacity' => bless( {
                                                                        'class' => 'XML::Pastor::Builtin::string',
                                                                        'metaClass' => 'OSCARS::Pastor::Meta',
                                                                        'minOccurs' => '0',
                                                                        'name' => 'maximumReservableCapacity',
                                                                        'scope' => 'local',
                                                                        'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                        'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'minimumReservableCapacity' => bless( {
                                                                        'class' => 'XML::Pastor::Builtin::string',
                                                                        'metaClass' => 'OSCARS::Pastor::Meta',
                                                                        'minOccurs' => '0',
                                                                        'name' => 'minimumReservableCapacity',
                                                                        'scope' => 'local',
                                                                        'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                        'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'remoteLinkId' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::string',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'remoteLinkId',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                           'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'trafficEngineeringMetric' => bless( {
                                                                       'class' => 'XML::Pastor::Builtin::string',
                                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                                       'name' => 'trafficEngineeringMetric',
                                                                       'scope' => 'local',
                                                                       'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                       'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'unreservedCapacity' => bless( {
                                                                 'class' => 'XML::Pastor::Builtin::string',
                                                                 'metaClass' => 'OSCARS::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'unreservedCapacity',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                                 'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                               }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'remoteLinkId',
                                 'trafficEngineeringMetric',
                                 'capacity',
                                 'maximumReservableCapacity',
                                 'minimumReservableCapacity',
                                 'granularity',
                                 'unreservedCapacity',
                                 'linkProtectionTypes',
                                 'administrativeGroups',
                                 'SwitchingCapabilityDescriptors'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'CtrlPlaneLinkContent',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::ns002::Type::CtrlPlaneLinkContent>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_id>(), B<id>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<SwitchingCapabilityDescriptors>()      - See L<OSCARS::ns002::Type::CtrlPlaneSwcapContent>.

=item B<administrativeGroups>()      - See L<OSCARS::ns002::Type::CtrlPlaneAdministrativeGroup>.

=item B<capacity>()      - See L<XML::Pastor::Builtin::string>.

=item B<granularity>()      - See L<XML::Pastor::Builtin::string>.

=item B<linkProtectionTypes>()      - See L<XML::Pastor::Builtin::string>.

=item B<maximumReservableCapacity>()      - See L<XML::Pastor::Builtin::string>.

=item B<minimumReservableCapacity>()      - See L<XML::Pastor::Builtin::string>.

=item B<remoteLinkId>()      - See L<XML::Pastor::Builtin::string>.

=item B<trafficEngineeringMetric>()      - See L<XML::Pastor::Builtin::string>.

=item B<unreservedCapacity>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
