
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::ns002::Type::Lifetime;

use OSCARS::ns002::Type::Duration;
use OSCARS::ns002::Type::TimeContent;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::ns002::Type::Lifetime->mk_accessors( qw(_id _direction start end duration));

# Attribute accessor aliases

sub id { &_id; }
sub direction { &_direction; }

OSCARS::ns002::Type::Lifetime->XmlSchemaType( bless( {
                 'attributeInfo' => {
                                    'direction' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'metaClass' => 'OSCARS::Pastor::Meta',
                                                          'name' => 'direction',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema',
                                                          'use' => 'optional'
                                                        }, 'XML::Pastor::Schema::Attribute' ),
                                    'id' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::string',
                                                   'metaClass' => 'OSCARS::Pastor::Meta',
                                                   'name' => 'id',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                   'type' => 'string|http://www.w3.org/2001/XMLSchema',
                                                   'use' => 'required'
                                                 }, 'XML::Pastor::Schema::Attribute' )
                                  },
                 'attributePrefix' => '_',
                 'attributes' => [
                                   'id',
                                   'direction'
                                 ],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::ns002::Type::Lifetime',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'duration' => bless( {
                                                       'class' => 'OSCARS::ns002::Type::Duration',
                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'duration',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                       'type' => 'Duration|http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'end' => bless( {
                                                  'class' => 'OSCARS::ns002::Type::TimeContent',
                                                  'metaClass' => 'OSCARS::Pastor::Meta',
                                                  'minOccurs' => '0',
                                                  'name' => 'end',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                  'type' => 'TimeContent|http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
                                                }, 'XML::Pastor::Schema::Element' ),
                                  'start' => bless( {
                                                    'class' => 'OSCARS::ns002::Type::TimeContent',
                                                    'metaClass' => 'OSCARS::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'start',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/',
                                                    'type' => 'TimeContent|http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
                                                  }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'start',
                                 'end',
                                 'duration'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'Lifetime',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::ns002::Type::Lifetime>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_direction>(), B<direction>()      - See L<XML::Pastor::Builtin::string>.

=item B<_id>(), B<id>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<duration>()      - See L<OSCARS::ns002::Type::Duration>.

=item B<end>()      - See L<OSCARS::ns002::Type::TimeContent>.

=item B<start>()      - See L<OSCARS::ns002::Type::TimeContent>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
