
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::eventContent;

use OSCARS::Type::localDetails;
use OSCARS::Type::msgDetails;
use OSCARS::Type::resDetails;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::eventContent->mk_accessors( qw(_id type timestamp userLogin errorSource errorCode errorMessage resDetails msgDetails localDetails));

# Attribute accessor aliases

sub id { &_id; }

OSCARS::Type::eventContent->XmlSchemaType( bless( {
                 'attributeInfo' => {
                                    'id' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::string',
                                                   'metaClass' => 'OSCARS::Pastor::Meta',
                                                   'name' => 'id',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                   'type' => 'string|http://www.w3.org/2001/XMLSchema',
                                                   'use' => 'required'
                                                 }, 'XML::Pastor::Schema::Attribute' )
                                  },
                 'attributePrefix' => '_',
                 'attributes' => [
                                   'id'
                                 ],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::eventContent',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'errorCode' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::string',
                                                        'maxOccurs' => '1',
                                                        'metaClass' => 'OSCARS::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'errorCode',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                        'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'errorMessage' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::string',
                                                           'maxOccurs' => '1',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'errorMessage',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                           'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'errorSource' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'maxOccurs' => '1',
                                                          'metaClass' => 'OSCARS::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'errorSource',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'localDetails' => bless( {
                                                           'class' => 'OSCARS::Type::localDetails',
                                                           'maxOccurs' => '1',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'localDetails',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                           'type' => 'localDetails|http://oscars.es.net/OSCARS'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'msgDetails' => bless( {
                                                         'class' => 'OSCARS::Type::msgDetails',
                                                         'maxOccurs' => '1',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'msgDetails',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                         'type' => 'msgDetails|http://oscars.es.net/OSCARS'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'resDetails' => bless( {
                                                         'class' => 'OSCARS::Type::resDetails',
                                                         'maxOccurs' => '1',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'resDetails',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                         'type' => 'resDetails|http://oscars.es.net/OSCARS'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'timestamp' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::long',
                                                        'metaClass' => 'OSCARS::Pastor::Meta',
                                                        'name' => 'timestamp',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                        'type' => 'long|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'type' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::string',
                                                   'metaClass' => 'OSCARS::Pastor::Meta',
                                                   'name' => 'type',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                   'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                 }, 'XML::Pastor::Schema::Element' ),
                                  'userLogin' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::string',
                                                        'maxOccurs' => '1',
                                                        'metaClass' => 'OSCARS::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'userLogin',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                        'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'type',
                                 'timestamp',
                                 'userLogin',
                                 'errorSource',
                                 'errorCode',
                                 'errorMessage',
                                 'resDetails',
                                 'msgDetails',
                                 'localDetails'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'eventContent',
                 'scope' => 'global',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::eventContent>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_id>(), B<id>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<errorCode>()      - See L<XML::Pastor::Builtin::string>.

=item B<errorMessage>()      - See L<XML::Pastor::Builtin::string>.

=item B<errorSource>()      - See L<XML::Pastor::Builtin::string>.

=item B<localDetails>()      - See L<OSCARS::Type::localDetails>.

=item B<msgDetails>()      - See L<OSCARS::Type::msgDetails>.

=item B<resDetails>()      - See L<OSCARS::Type::resDetails>.

=item B<timestamp>()      - See L<XML::Pastor::Builtin::long>.

=item B<type>()      - See L<XML::Pastor::Builtin::string>.

=item B<userLogin>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
