
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::forward;

use OSCARS::Type::forwardPayload;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::forward->mk_accessors( qw(payload payloadSender));

OSCARS::Type::forward->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::forward',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'payload' => bless( {
                                                      'class' => 'OSCARS::Type::forwardPayload',
                                                      'metaClass' => 'OSCARS::Pastor::Meta',
                                                      'name' => 'payload',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                      'type' => 'forwardPayload|http://oscars.es.net/OSCARS'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'payloadSender' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::string',
                                                            'metaClass' => 'OSCARS::Pastor::Meta',
                                                            'name' => 'payloadSender',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                            'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'payload',
                                 'payloadSender'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'forward',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::forward>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<payload>()      - See L<OSCARS::Type::forwardPayload>.

=item B<payloadSender>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
