
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::forwardReply;

use OSCARS::Type::createPathResponseContent;
use OSCARS::Type::createReply;
use OSCARS::Type::listReply;
use OSCARS::Type::modifyResReply;
use OSCARS::Type::refreshPathResponseContent;
use OSCARS::Type::resDetails;
use OSCARS::Type::teardownPathResponseContent;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::forwardReply->mk_accessors( qw(contentType createReservation modifyReservation cancelReservation queryReservation listReservations createPath refreshPath teardownPath));

OSCARS::Type::forwardReply->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::forwardReply',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'cancelReservation' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::string',
                                                                'maxOccurs' => '1',
                                                                'metaClass' => 'OSCARS::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'cancelReservation',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                                'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'contentType' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'metaClass' => 'OSCARS::Pastor::Meta',
                                                          'name' => 'contentType',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'createPath' => bless( {
                                                         'class' => 'OSCARS::Type::createPathResponseContent',
                                                         'maxOccurs' => '1',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'createPath',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                         'type' => 'createPathResponseContent|http://oscars.es.net/OSCARS'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'createReservation' => bless( {
                                                                'class' => 'OSCARS::Type::createReply',
                                                                'maxOccurs' => '1',
                                                                'metaClass' => 'OSCARS::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'createReservation',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                                'type' => 'createReply|http://oscars.es.net/OSCARS'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'listReservations' => bless( {
                                                               'class' => 'OSCARS::Type::listReply',
                                                               'maxOccurs' => '1',
                                                               'metaClass' => 'OSCARS::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'listReservations',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                               'type' => 'listReply|http://oscars.es.net/OSCARS'
                                                             }, 'XML::Pastor::Schema::Element' ),
                                  'modifyReservation' => bless( {
                                                                'class' => 'OSCARS::Type::modifyResReply',
                                                                'maxOccurs' => '1',
                                                                'metaClass' => 'OSCARS::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'modifyReservation',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                                'type' => 'modifyResReply|http://oscars.es.net/OSCARS'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'queryReservation' => bless( {
                                                               'class' => 'OSCARS::Type::resDetails',
                                                               'maxOccurs' => '1',
                                                               'metaClass' => 'OSCARS::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'queryReservation',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                               'type' => 'resDetails|http://oscars.es.net/OSCARS'
                                                             }, 'XML::Pastor::Schema::Element' ),
                                  'refreshPath' => bless( {
                                                          'class' => 'OSCARS::Type::refreshPathResponseContent',
                                                          'maxOccurs' => '1',
                                                          'metaClass' => 'OSCARS::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'refreshPath',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                          'type' => 'refreshPathResponseContent|http://oscars.es.net/OSCARS'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'teardownPath' => bless( {
                                                           'class' => 'OSCARS::Type::teardownPathResponseContent',
                                                           'maxOccurs' => '1',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'teardownPath',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                           'type' => 'teardownPathResponseContent|http://oscars.es.net/OSCARS'
                                                         }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'contentType',
                                 'createReservation',
                                 'modifyReservation',
                                 'cancelReservation',
                                 'queryReservation',
                                 'listReservations',
                                 'createPath',
                                 'refreshPath',
                                 'teardownPath'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'forwardReply',
                 'scope' => 'global',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::forwardReply>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<cancelReservation>()      - See L<XML::Pastor::Builtin::string>.

=item B<contentType>()      - See L<XML::Pastor::Builtin::string>.

=item B<createPath>()      - See L<OSCARS::Type::createPathResponseContent>.

=item B<createReservation>()      - See L<OSCARS::Type::createReply>.

=item B<listReservations>()      - See L<OSCARS::Type::listReply>.

=item B<modifyReservation>()      - See L<OSCARS::Type::modifyResReply>.

=item B<queryReservation>()      - See L<OSCARS::Type::resDetails>.

=item B<refreshPath>()      - See L<OSCARS::Type::refreshPathResponseContent>.

=item B<teardownPath>()      - See L<OSCARS::Type::teardownPathResponseContent>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
