
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::layer3Info;


our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::layer3Info->mk_accessors( qw(srcHost destHost protocol srcIpPort destIpPort dscp));

OSCARS::Type::layer3Info->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::layer3Info',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'destHost' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::string',
                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                       'name' => 'destHost',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                       'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'destIpPort' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::int',
                                                         'maxOccurs' => '1',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'destIpPort',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                         'type' => 'int|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'dscp' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::string',
                                                   'maxOccurs' => '1',
                                                   'metaClass' => 'OSCARS::Pastor::Meta',
                                                   'minOccurs' => '0',
                                                   'name' => 'dscp',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                   'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                 }, 'XML::Pastor::Schema::Element' ),
                                  'protocol' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::string',
                                                       'maxOccurs' => '1',
                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'protocol',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                       'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'srcHost' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::string',
                                                      'metaClass' => 'OSCARS::Pastor::Meta',
                                                      'name' => 'srcHost',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                      'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'srcIpPort' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::int',
                                                        'maxOccurs' => '1',
                                                        'metaClass' => 'OSCARS::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'srcIpPort',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                        'type' => 'int|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'srcHost',
                                 'destHost',
                                 'protocol',
                                 'srcIpPort',
                                 'destIpPort',
                                 'dscp'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'layer3Info',
                 'scope' => 'global',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::layer3Info>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<destHost>()      - See L<XML::Pastor::Builtin::string>.

=item B<destIpPort>()      - See L<XML::Pastor::Builtin::int>.

=item B<dscp>()      - See L<XML::Pastor::Builtin::string>.

=item B<protocol>()      - See L<XML::Pastor::Builtin::string>.

=item B<srcHost>()      - See L<XML::Pastor::Builtin::string>.

=item B<srcIpPort>()      - See L<XML::Pastor::Builtin::int>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
