
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::layer2Info;

use OSCARS::Type::vlanTag;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::layer2Info->mk_accessors( qw(srcVtag destVtag srcEndpoint destEndpoint));

OSCARS::Type::layer2Info->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::layer2Info',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'destEndpoint' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::string',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'name' => 'destEndpoint',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                           'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'destVtag' => bless( {
                                                       'class' => 'OSCARS::Type::vlanTag',
                                                       'maxOccurs' => '1',
                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'destVtag',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                       'type' => 'vlanTag|http://oscars.es.net/OSCARS'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'srcEndpoint' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'metaClass' => 'OSCARS::Pastor::Meta',
                                                          'name' => 'srcEndpoint',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'srcVtag' => bless( {
                                                      'class' => 'OSCARS::Type::vlanTag',
                                                      'maxOccurs' => '1',
                                                      'metaClass' => 'OSCARS::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'srcVtag',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                      'type' => 'vlanTag|http://oscars.es.net/OSCARS'
                                                    }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'srcVtag',
                                 'destVtag',
                                 'srcEndpoint',
                                 'destEndpoint'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'layer2Info',
                 'scope' => 'global',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::layer2Info>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<destEndpoint>()      - See L<XML::Pastor::Builtin::string>.

=item B<destVtag>()      - See L<OSCARS::Type::vlanTag>.

=item B<srcEndpoint>()      - See L<XML::Pastor::Builtin::string>.

=item B<srcVtag>()      - See L<OSCARS::Type::vlanTag>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
