
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::listReply;

use OSCARS::Type::resDetails;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::listReply->mk_accessors( qw(resDetails totalResults));

OSCARS::Type::listReply->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::listReply',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'resDetails' => bless( {
                                                         'class' => 'OSCARS::Type::resDetails',
                                                         'maxOccurs' => 'unbounded',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'resDetails',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                         'type' => 'resDetails|http://oscars.es.net/OSCARS'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'totalResults' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::int',
                                                           'metaClass' => 'OSCARS::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'totalResults',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                           'type' => 'int|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'resDetails',
                                 'totalResults'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'listReply',
                 'scope' => 'global',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::listReply>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<resDetails>()      - See L<OSCARS::Type::resDetails>.

=item B<totalResults>()      - See L<XML::Pastor::Builtin::int>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
