
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::modifyResReply;

use OSCARS::Type::resDetails;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::modifyResReply->mk_accessors( qw(reservation));

OSCARS::Type::modifyResReply->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::modifyResReply',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'reservation' => bless( {
                                                          'class' => 'OSCARS::Type::resDetails',
                                                          'metaClass' => 'OSCARS::Pastor::Meta',
                                                          'name' => 'reservation',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                          'type' => 'resDetails|http://oscars.es.net/OSCARS'
                                                        }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'reservation'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'modifyResReply',
                 'scope' => 'global',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::modifyResReply>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<reservation>()      - See L<OSCARS::Type::resDetails>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
