
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Wed Jul  1 15:32:04 2009'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package OSCARS::Type::pathInfo;

use OSCARS::Type::layer2Info;
use OSCARS::Type::layer3Info;
use OSCARS::Type::mplsInfo;
use OSCARS::ns002::Type::CtrlPlanePathContent;

our @ISA=qw(XML::Pastor::ComplexType);

OSCARS::Type::pathInfo->mk_accessors( qw(pathSetupMode pathType path layer2Info layer3Info mplsInfo));

OSCARS::Type::pathInfo->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'OSCARS::Type::pathInfo',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'layer2Info' => bless( {
                                                         'class' => 'OSCARS::Type::layer2Info',
                                                         'maxOccurs' => '1',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'layer2Info',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                         'type' => 'layer2Info|http://oscars.es.net/OSCARS'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'layer3Info' => bless( {
                                                         'class' => 'OSCARS::Type::layer3Info',
                                                         'maxOccurs' => '1',
                                                         'metaClass' => 'OSCARS::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'layer3Info',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                         'type' => 'layer3Info|http://oscars.es.net/OSCARS'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'mplsInfo' => bless( {
                                                       'class' => 'OSCARS::Type::mplsInfo',
                                                       'maxOccurs' => '1',
                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'mplsInfo',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                       'type' => 'mplsInfo|http://oscars.es.net/OSCARS'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'path' => bless( {
                                                   'class' => 'OSCARS::ns002::Type::CtrlPlanePathContent',
                                                   'maxOccurs' => '1',
                                                   'metaClass' => 'OSCARS::Pastor::Meta',
                                                   'minOccurs' => '0',
                                                   'name' => 'path',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                   'type' => 'CtrlPlanePathContent|http://ogf.org/schema/network/topology/ctrlPlane/20080828/'
                                                 }, 'XML::Pastor::Schema::Element' ),
                                  'pathSetupMode' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::string',
                                                            'metaClass' => 'OSCARS::Pastor::Meta',
                                                            'minOccurs' => '1',
                                                            'name' => 'pathSetupMode',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                            'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                  'pathType' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::string',
                                                       'maxOccurs' => '1',
                                                       'metaClass' => 'OSCARS::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'pathType',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://oscars.es.net/OSCARS',
                                                       'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'pathSetupMode',
                                 'pathType',
                                 'path',
                                 'layer2Info',
                                 'layer3Info',
                                 'mplsInfo'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'OSCARS::Pastor::Meta',
                 'name' => 'pathInfo',
                 'scope' => 'global',
                 'targetNamespace' => 'http://oscars.es.net/OSCARS'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<OSCARS::Type::pathInfo>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Wed Jul  1 15:32:04 2009'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<layer2Info>()      - See L<OSCARS::Type::layer2Info>.

=item B<layer3Info>()      - See L<OSCARS::Type::layer3Info>.

=item B<mplsInfo>()      - See L<OSCARS::Type::mplsInfo>.

=item B<path>()      - See L<OSCARS::ns002::Type::CtrlPlanePathContent>.

=item B<pathSetupMode>()      - See L<XML::Pastor::Builtin::string>.

=item B<pathType>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
