#!/usr/bin/bash

CHROOT=epel-7-x86_64
MOCK_RESULTS=/home/vagrant/mock-results/

if [ -z "$1" ]; then
    echo "Usage: $0 SRPM"
    echo ""
    echo "Must specify the SRPM to build"
    exit 1
fi

sudo mock -r $CHROOT --clean
sudo mock -r $CHROOT --init
sudo mock -r $CHROOT --resultdir=${MOCK_RESULTS}${CHROOT} --arch=x86_64 $1
