%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Data-Validate-IP
Version:        0.08
Release:        1%{?dist}
Summary:        Ip validation methods
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Data-Validate-IP/
Source0:        http://www.cpan.org/modules/by-module/Data/Data-Validate-IP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(Net::Netmask)
Requires:       perl(Test::Simple)
Requires:       perl

%description
This module collects ip validation routines to make input validation, and
untainting easier and more readable.

%prep
%setup -q -n Data-Validate-IP-%{version}

%build
%{__perl} Makefile.PL INSTALL_BASE=/usr
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
/usr/*

%changelog
* Wed Mar 04 2009 Jason Zurawski 0.08-1
- Specfile autogenerated by cpanspec 1.77.
