%{!?perl_prefix: %define perl_prefix %(eval "`%{__perl} -V:installprefix`"; echo $installprefix)}
%{!?perl_style: %define perl_style %(eval "`%{__perl} -V:installstyle`"; echo $installstyle)}

Name:           perl-XML-LibXML
Version:        1.69
Release:        1%{?dist}
Summary:        Perl Binding for libxml2
License:        Distributable, see LICENSE
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/XML-LibXML/
Source0:        http://www.cpan.org/modules/by-module/XML/XML-LibXML-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Buildarch:      i386
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(XML::LibXML::Common) >= 0.13
BuildRequires:  perl(XML::NamespaceSupport) >= 1.07
BuildRequires:  perl(XML::SAX) >= 0.11
Requires:       perl
Requires:       libxml2
Requires:       libxml2-devel
Requires:       perl(XML::LibXML::Common) >= 0.13
Requires:       perl(XML::NamespaceSupport) >= 1.07
Requires:       perl(XML::SAX) >= 0.11

%description
This module is an interface to libxml2, providing XML and HTML parsers with
DOM, SAX and XMLReader interfaces, a large subset of DOM Layer 3 interface
and a XML::XPath-like interface to XPath API of libxml2. The module is
split into several packages which are not described in this section; unless
stated otherwise, you only need to use XML::LibXML; in your programs.

%prep
%setup -q -n XML-LibXML-%{version}

%build
%{__perl} Makefile.PL INSTALL_BASE=%{perl_prefix} OPTIMIZE="$RPM_OPT_FLAGS"
%{__perl} -pi -e 's/^\tLD_RUN_PATH=[^\s]+\s*/\t/' Makefile
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README
/usr/*

%post
ln -s %{perl_prefix}/%{perl_style}/Data %{perl_prefix}/%{perl_style}/vendor_perl
ln -s %{perl_prefix}/%{perl_style}/auto %{perl_prefix}/%{perl_style}/vendor_perl

%changelog
* Thu Mar 12 2009 Jason Zurawski 1.69-1
- Specfile autogenerated by cpanspec 1.77.
