# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Build a build machine as the default
  config.vm.define "ps-rpmbuild-el7", primary: true, autostart: true do |build|
    # set box to official CentOS 7 image
    build.vm.box = "centos/7"
    # explcitly set shared folder to virtualbox type. If not set will choose rsync 
    # which is just a one-way share that is less useful in this context
    build.vm.synced_folder "..", "/vagrant", type: "virtualbox"
    # Set hostname
    build.vm.hostname = "ps-rpmbuild-el7"
    
    # Enable IPv4. Cannot be directly before or after line that sets IPv6 address. Looks
    # to be a strange bug where IPv6 and IPv4 mixed-up by vagrant otherwise and one 
    #interface will appear not to have an address. If you look at network-scripts file
    # you will see a mangled result where IPv4 is set for IPv6 or vice versa
    build.vm.network "private_network", ip: "10.0.1.10"
    
    # Enable IPv6. Currently only supports setting via static IP. Address below in the
    # reserved local address range for IPv6
    build.vm.network "private_network", ip: "fdac:218a:75e5:69c8::b0"
    
    #Disable selinux
    build.vm.provision "shell", inline: <<-SHELL
        sed -i s/SELINUX=enforcing/SELINUX=permissive/g /etc/selinux/config
    SHELL
    
    #reload VM since selinux requires reboot. Requires `vagrant plugin install vagrant-reload`
    build.vm.provision :reload
    
    #Install all requirements and perform initial setup
    build.vm.provision "shell", inline: <<-SHELL
    
        ## install yum dependencies
        yum install -y epel-release
        yum install -y http://software.internet2.edu/rpms/el7/x86_64/RPMS.main/perfSONAR-repo-0.9-1.noarch.rpm
        yum clean all
        yum install -y perfSONAR-repo-staging perfSONAR-repo-nightly
        yum clean all
        yum install -y gcc\
            kernel-devel\
            kernel-headers\
            dkms\
            make\
            bzip2\
            perl\
            mock\
            git\
            rpm-build\
            rpmdevtools\
            httpd\
            createrepo
        
        ## create build environment directories
        mkdir -m 755 -p /var/www/html/repo
        mkdir -m 755 -p /home/vagrant/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        mkdir -m 755 -p /home/vagrant/mock-results/epel-7-x86_64
        
        ## create .rpmmacros file
        cat > /home/vagrant/.rpmmacros << EOF
        %_topdir /home/vagrant/rpmbuild
        %packager vagrant
        %_smp_mflags -j3
EOF
        ## make sure permissions on home directory are good
        chown -R vagrant:vagrant /home/vagrant
             
        ## enable httpd for repo
        systemctl enable httpd
        systemctl start httpd
        
        ## symlink scripts
        chmod 755 /vagrant/rpms/scripts/*
        ln -fs /vagrant/rpms/scripts/* /usr/bin/
        
    SHELL
  end
  
  config.vm.define "ps-rpminstall-el7", primary: false, autostart: false do |install|
    # set box to official CentOS 7 image
    install.vm.box = "centos/7"
    # explcitly set shared folder to virtualbox type. If not set will choose rsync 
    # which is just a one-way share that is less useful in this context
    install.vm.synced_folder "..", "/vagrant", type: "virtualbox"
    # Set hostname
    install.vm.hostname = "ps-rpminstall-el7"
    
    # Enable IPv4. Cannot be directly before or after line that sets IPv6 address. Looks
    # to be a strange bug where IPv6 and IPv4 mixed-up by vagrant otherwise and one 
    #interface will appear not to have an address. If you look at network-scripts file
    # you will see a mangled result where IPv4 is set for IPv6 or vice versa
    install.vm.network "private_network", ip: "10.0.1.11"
    
    # Enable IPv6. Currently only supports setting via static IP. Address below in the
    # reserved local address range for IPv6
    install.vm.network "private_network", ip: "fdac:218a:75e5:69c8::b1"
    
    #Disable selinux
    install.vm.provision "shell", inline: <<-SHELL
        sed -i s/SELINUX=enforcing/SELINUX=permissive/g /etc/selinux/config
    SHELL
    
    #reload VM since selinux requires reboot. Requires `vagrant plugin install vagrant-reload`
    install.vm.provision :reload
    
    #Install all requirements and perform initial setup
    install.vm.provision "shell", inline: <<-SHELL
    
        ## install yum dependencies
        yum install -y epel-release
        yum install -y http://software.internet2.edu/rpms/el7/x86_64/RPMS.main/perfSONAR-repo-0.9-1.noarch.rpm
        yum clean all
        yum install -y perfSONAR-repo-staging perfSONAR-repo-nightly
        yum clean all
        yum install -y gcc\
            kernel-devel\
            kernel-headers\
            dkms\
            make\
            bzip2\
            perl
        cat > /etc/yum.repos.d/ps-rpmbuild.repo << EOF
[ps-rpmbuild]
name = perfSONAR RPM Build VM
baseurl = http://10.0.1.10/repo/
enabled = 1
protect = 0
gpgcheck = 0
proxy = _none_
EOF
        chmod 644 /etc/yum.repos.d/ps-rpmbuild.repo
    SHELL
  end
end
